server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:db}:${DB_PORT:5432}/${DB_NAME:todo}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:postgres}
    thymeleaf:
      cache: false

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  flyway:
    enabled: true

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            scope:
              - read:user
              - user:email
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
            user-name-attribute: login